### ISSUE TITLE
MuleSoft SMB Connector not working

### ISSUE THREAD

**Issue by Savithab22** [nuggetman/smb-connector#7] opened 2018-10-24 05:42 UTC
Hi,
We are trying to configure SMB Connector in MuleSoft Mule 3.9.1 run-time version. We are running into the below error while configuring the SMB connector to list directory. Could you please assist? PFB the configuration

<smb:config name="SMB_Connector__Configuration" domain="${domain}"
		host="${host}" path="${path}"
		username="${username}" password="${password}" doc:name="SMB Connector: Configuration" />

<flow name="mule-smb-Flow">
		<poll doc:name="Poll">
			<fixed-frequency-scheduler frequency="1"
				timeUnit="MINUTES" />
			<smb:directory-list config-ref="SMB_Connector__Configuration"
				dirName="/" doc:name="SMB Connector" />
		</poll>
		<logger message="#[message]" level="INFO" doc:name="Logger" />
	</flow>

Root Exception stack trace:
jcifs.smb.SmbException: Invalid operation for  service
	at jcifs.smb.SmbTree.send(SmbTree.java:92)
	at jcifs.smb.SmbFile.send(SmbFile.java:729)
	at jcifs.smb.SmbFile.queryPath(SmbFile.java:1308)
	at jcifs.smb.SmbFile.exists(SmbFile.java:1362)
	at jcifs.smb.SmbFile.canRead(SmbFile.java:1404)
	at org.mule.modules.smb.internal.SmbClient.connect(SmbClient.java:125)
	at org.mule.modules.smb.config.SmbConnectorConfig.connect(SmbConnectorConfig.java:186)
	at org.mule.modules.smb.generated.connectivity.SmbConnectorConfigSmbConnectorAdapter.connect(SmbConnectorConfigSmbConnectorAdapter.java:34)
	at org.mule.modules.smb.generated.connectivity.SmbConnectorConfigSmbConnectorAdapter.connect(SmbConnectorConfigSmbConnectorAdapter.java:10)

**Comment by nuggetman** [comment] 2018-10-31 13:50
Can you share any details regarding the directory you are trying to list so I can reproduce the error?

**Comment by nuggetman** [comment] 2019-04-03 22:59
closing issue due to non-response.

**Closed by nuggetman** 2019-04-03 22:59 UTC
