### ISSUE TITLE
SMB Connector - Mule 3

### ISSUE THREAD

**Issue by selmech** [nuggetman/smb-connector#19] opened 2020-02-04 14:04 UTC
I have a case that is related to the smb connector version.
So far we have used the smb connector version 1.0.0 to get files from PCs running Windows 7. 
Now we have to use PCs with Windows 10, but we could not read files from the samba share directory.

We have also tried to use the Samba connector 1.2.0, i.e. we were able to get files from PCs running Windows 10.
But on the other hand, when we tried to write files into other Samba shares, it didn't work, we got an "ACCESS DENIED" problem, even though it used the same configuration.
Also, the Samba connector version (1.2.0) does not support reading metadata.

**Comment by nuggetman** [comment] 2020-02-21 21:41
Interesting, v1.2.0 of the connector has been successfully tested against Windows 10 so in principal it should work. Checking the security audit log on the share host should give some better indication of the cause of the issue.

**Comment by nuggetman** [comment] 2020-04-03 02:30
Not sure this issue is related to the first one, however if the schema is missing in Mule this can often be resolved by dragging the connector onto the canvas in the flow to update the XML config.

**Closed** 2020-06-04 00:43 UTC
Labels: help wanted
